{"timestamp":"2025-05-12T00:39:34.654801","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-05-12T00:39:34.655408","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/yfinance_DAG.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-05-12T00:39:40.094653Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:40.095922Z","level":"error","event":"  File \"/opt/airflow/dags/jobs/YFinance.py\", line 15, in <module>","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:40.100797Z","level":"error","event":"    db = client[MONGODB_DB]","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:40.101479Z","level":"error","event":"         ~~~~~~^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:40.102000Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 1326, in __getitem__","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:40.102484Z","level":"error","event":"    return database.Database(self, name)","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:40.102801Z","level":"error","event":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:40.103115Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/database.py\", line 125, in __init__","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:40.103670Z","level":"error","event":"    raise TypeError(f\"name must be an instance of str, not {type(name)}\")","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:40.104145Z","level":"error","event":"TypeError: name must be an instance of str, not <class 'NoneType'>","chan":"stderr","logger":"task"}
{"timestamp":"2025-05-12T00:39:43.103638","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CalledProcessError","exc_value":"Command '['python', 'dags/jobs/YFinance.py']' returned non-zero exit status 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/yfinance_DAG.py","lineno":14,"name":"<lambda>"},{"filename":"/usr/local/lib/python3.12/subprocess.py","lineno":571,"name":"run"}]}]}
